INF_OK = 0
INF_RESET = 1
INF_NOT_HEAR_WELL = 2
INF_NO_MATCHING_NAME  = 3
INF_NO_TARGET_WORDS = 4
INF_MULTIPLE_MATCH = 5

SUCCESS = 0
ERR_EXCEPTION = 1
ERR_TIMEOUT = 2
ERR_TYPEERROR = 3

INTENT_OTHERS = 0
INTENT_HELP = INTENT_OTHERS + 1
INTENT_YES = INTENT_HELP + 1
INTENT_NO = INTENT_YES + 1
INTENT_CANCEL = INTENT_NO + 1
INTENT_RETRY = INTENT_CANCEL + 1
INTENT_GENERAL_MAX = INTENT_RETRY

INTENT_TEL = INTENT_GENERAL_MAX + 1
INTENT_CALL_POLICE = INTENT_TEL + 1
INTENT_CALL_EMERGENCY = INTENT_CALL_POLICE + 1
INTENT_SEND_LINE_MESSAGE = INTENT_CALL_EMERGENCY + 1
INTENT_SEND_SHORT_MESSAGE = INTENT_SEND_LINE_MESSAGE + 1
INTENT_SCENARIO_MAX = INTENT_SEND_SHORT_MESSAGE

INTENT_GENKIKAI = INTENT_SCENARIO_MAX + 1
INTENT_GENKIKAI_ADMIN = INTENT_GENKIKAI + 1
INTENT_GENKIKAI_MYRESERVATION = INTENT_GENKIKAI_ADMIN + 1
INTENT_GENKIKAI_NEWS = INTENT_GENKIKAI_MYRESERVATION + 1
INTENT_GENKIKAI_MANAGE_RECORDS = INTENT_GENKIKAI_NEWS + 1
INTENT_GENKIKAI_MANAGE_RESERVATIONS = INTENT_GENKIKAI_MANAGE_RECORDS + 1
INTENT_GENKIKAI_MAX = INTENT_GENKIKAI_MANAGE_RESERVATIONS

INTENT_MAX = INTENT_GENKIKAI_MAX

# display string
intents = {
    INTENT_OTHERS:"others",
    INTENT_HELP:"help",
    INTENT_YES:"yes",
    INTENT_NO: "no",
    INTENT_CANCEL: "cancel",
    INTENT_RETRY: "retry",
    INTENT_TEL: "tel",
    INTENT_CALL_POLICE: "call_police",
    INTENT_CALL_EMERGENCY: "call_emergency",
    INTENT_SEND_LINE_MESSAGE:"send_line_message",
    INTENT_SEND_SHORT_MESSAGE: "send_short_message",
    INTENT_GENKIKAI: "genkikai",
    INTENT_GENKIKAI_ADMIN: "genkikai_admin",
    INTENT_GENKIKAI_MYRESERVATION: "genkikai_myreservation",
    INTENT_GENKIKAI_NEWS: "genkikai_news",
    INTENT_GENKIKAI_MANAGE_RECORDS: "genkikai_manage_records",
    INTENT_GENKIKAI_MANAGE_RESERVATIONS: "genkikai_manage_reservations",
}